on:
    workflow_dispatch:
    push:
        branches: main

name: Quarto Publish

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Quarto
              uses: quarto-dev/quarto-actions/setup@v2

            - name: Mamba and samurai env installation
              uses: mamba-org/setup-micromamba@v1
              with:
                  environment-file: environment.yml
                  environment-name: env
                  cache-environment: true

            - name: Render and Publish
              uses: quarto-dev/quarto-actions/publish@v2
              with:
                  path: talk.qmd
                  target: gh-pages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
